-- Baseline migration (issue #19). Hand-edited from drizzle-kits generated output.
--
-- WHY every statement uses IF NOT EXISTS: this baseline must be a safe no-op on the
-- users already-populated ~/.trove/trove.db (created historically by the old
-- CREATE TABLE IF NOT EXISTS DDL in schema.ts). On such a DB the migrator has no
-- __drizzle_migrations row yet, so it WILL run this file once; if it used plain
-- CREATE TABLE it would error on the existing tables and the migration would roll
-- back, leaving trove unusable. Making every create idempotent lets the baseline run
-- as a pure no-op there, get recorded, and leave all data 100 percent intact. On a
-- fresh DB the very same statements create the whole physical schema.
--
-- FUTURE migrations (0001+) generated by drizzle-kit generate need NOT be idempotent:
-- they run exactly once, gated by __drizzle_migrations, and may use plain CREATE/ALTER.
--
-- The FTS5 virtual table messages_fts and its 3 triggers (messages_ai/ad/au) at the
-- end of this file are copied verbatim from the historical SCHEMA_SQL. drizzle-kit
-- cannot model them, so they are managed MANUALLY here and future generate runs will
-- never touch them. The runtime migrator splits this file only on the statement marker
-- comment between statements and runs each chunk as one prepared statement, so the
-- semicolons inside the trigger bodies stay within a single chunk.
CREATE TABLE IF NOT EXISTS `highlights` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`session_id` text NOT NULL,
	`message_uid` text,
	`message_seq` integer,
	`text` text NOT NULL,
	`note` text,
	`created_at` integer NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `idx_highlights_session` ON `highlights` (`session_id`);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `kv` (
	`key` text PRIMARY KEY NOT NULL,
	`value` text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `messages` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`uid` text,
	`session_id` text NOT NULL,
	`seq` integer NOT NULL,
	`role` text NOT NULL,
	`parent_uid` text,
	`timestamp` integer,
	`text` text NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `idx_messages_session` ON `messages` (`session_id`);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `session_meta` (
	`session_id` text PRIMARY KEY NOT NULL,
	`custom_name` text,
	`starred` integer DEFAULT 0 NOT NULL,
	`tags` text,
	`notes` text,
	`hidden` integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `sessions` (
	`id` text PRIMARY KEY NOT NULL,
	`agent` text NOT NULL,
	`native_id` text NOT NULL,
	`source_path` text NOT NULL,
	`source_medium` text NOT NULL,
	`project_path` text,
	`created_at` integer,
	`updated_at` integer,
	`size_bytes` integer,
	`turn_count` integer,
	`message_count` integer,
	`model` text,
	`source_title` text,
	`kind` text,
	`agent_specific` text,
	`raw_path` text,
	`content_hash` text NOT NULL,
	`source_mtime` integer,
	`imported_at` integer NOT NULL,
	`source_gone` integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `idx_sessions_agent` ON `sessions` (`agent`);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `idx_sessions_source_path` ON `sessions` (`source_path`);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `idx_sessions_updated` ON `sessions` (`updated_at` DESC);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `summaries` (
	`session_id` text PRIMARY KEY NOT NULL,
	`text` text NOT NULL,
	`created_at` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `tombstones` (
	`source_path` text PRIMARY KEY NOT NULL,
	`id` text,
	`deleted_at` integer
);
--> statement-breakpoint
CREATE VIRTUAL TABLE IF NOT EXISTS messages_fts USING fts5(
  text,
  content='messages',
  content_rowid='id',
  tokenize="unicode61 remove_diacritics 2"
);
--> statement-breakpoint
CREATE TRIGGER IF NOT EXISTS messages_ai AFTER INSERT ON messages BEGIN
  INSERT INTO messages_fts(rowid, text) VALUES (new.id, new.text);
END;
--> statement-breakpoint
CREATE TRIGGER IF NOT EXISTS messages_ad AFTER DELETE ON messages BEGIN
  INSERT INTO messages_fts(messages_fts, rowid, text) VALUES ('delete', old.id, old.text);
END;
--> statement-breakpoint
CREATE TRIGGER IF NOT EXISTS messages_au AFTER UPDATE ON messages BEGIN
  INSERT INTO messages_fts(messages_fts, rowid, text) VALUES ('delete', old.id, old.text);
  INSERT INTO messages_fts(rowid, text) VALUES (new.id, new.text);
END;
